# Generated by Django 5.2.6 on 2025-09-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('vid', models.CharField(choices=[('хетчбек', 'хетчбек'), ('седан', 'седан'), ('универсал', 'универсал'), ('купе', 'купе'), ('кроссовер', 'кроссовер'), ('пикап', 'пикап'), ('внедорожник', 'внедорожник'), ('минивэн', 'минивэн'), ('фургон', 'фургон'), ('кроссовер', 'кроссовер'), ('пикап', 'пикап'), ('внедорожник', 'внедорожник'), ('минивэн', 'минивэн'), ('фургон', 'фургон')])),
                ('year', models.PositiveIntegerField()),
                ('whatcost', models.PositiveIntegerField(help_text='How much cost?')),
                ('picture', models.ImageField(upload_to='posters/')),
            ],
        ),
    ]
